const emojiImagePaths = {
  growthChart: "./growth-chart.png",
  barChart: "./bar-chart.png",
  gears: "./gears.png",
  briefcase: "./briefcase.png",
  calendar: "./calendar.png",
  memo: "./memo.png",
  fileFolder: "./file-folder.png",
  link: "./link.png",
  cardIndexDividers: "./card-index-dividers.png",
  buildingConstruction: "./building-construction.png",
  receipt: "./receipt.png",
  clipboard: "./clipboard.png",
  lightBulb: "./light-bulb.png",
  checkMark: "./check-mark.png",
  pushpin: "./pushpin.png",
  paperclip: "./paperclip.png",
  handshake: "./handshake.png",
  moneyBag: "./money-bag.png",
  officeBuilding: "./office-building.png",
  downwardTrend: "./downward-trend.png",
  stockMarketUp: "./stock-market-up.png",
  womanTechnologist: "./woman-technologist.png",
  wrench: "./wrench.png",
};

export const customEmojis = [
  {
    id: "project_management",
    name: "Project Management",
    emojis: [
      {
        id: "📈",
        name: "Growth Chart",
        keywords: ["chart", "growth", "business"],
        skins: [{src: emojiImagePaths.growthChart}],
      },
      {
        id: "📊",
        name: "Bar Chart",
        keywords: ["chart", "bar", "statistics"],
        skins: [{src: emojiImagePaths.barChart}],
      },
      {
        id: "⚙️",
        name: "Gears",
        keywords: ["settings", "tools", "automation"],
        skins: [{src: emojiImagePaths.gears}],
      },
      {
        id: "💼",
        name: "Briefcase",
        keywords: ["work", "business", "office"],
        skins: [{src: emojiImagePaths.briefcase}],
      },
      {
        id: "📅",
        name: "Calendar",
        keywords: ["schedule", "date", "event"],
        skins: [{src: emojiImagePaths.calendar}],
      },
      {
        id: "📝",
        name: "Memo",
        keywords: ["note", "document", "reminder"],
        skins: [{src: emojiImagePaths.memo}],
      },
      {
        id: "📂",
        name: "File Folder",
        keywords: ["files", "storage", "organization"],
        skins: [{src: emojiImagePaths.fileFolder}],
      },
      {
        id: "🔗",
        name: "Link",
        keywords: ["connection", "url", "attachment"],
        skins: [{src: emojiImagePaths.link}],
      },
      {
        id: "🗂️",
        name: "Card Index Dividers",
        keywords: ["organize", "index", "files"],
        skins: [{src: emojiImagePaths.cardIndexDividers}],
      },
      {
        id: "🏗️",
        name: "Building Construction",
        keywords: ["build", "construction", "structure"],
        skins: [{src: emojiImagePaths.buildingConstruction}],
      },
      {
        id: "🧾",
        name: "Receipt",
        keywords: ["bill", "invoice", "proof"],
        skins: [{src: emojiImagePaths.receipt}],
      },
      {
        id: "📋",
        name: "Clipboard",
        keywords: ["note", "tasks", "checklist"],
        skins: [{src: emojiImagePaths.clipboard}],
      },
      {
        id: "💡",
        name: "Light Bulb",
        keywords: ["idea", "innovation", "bright"],
        skins: [{src: emojiImagePaths.lightBulb}],
      },
      {
        id: "✅",
        name: "Check Mark Button",
        keywords: ["complete", "done", "success"],
        skins: [{src: emojiImagePaths.checkMark}],
      },
      {
        id: "📌",
        name: "Pushpin",
        keywords: ["pin", "highlight", "important"],
        skins: [{src: emojiImagePaths.pushpin}],
      },
      {
        id: "🖇️",
        name: "Paperclip",
        keywords: ["attachment", "files", "clip"],
        skins: [{src: emojiImagePaths.paperclip}],
      },
    ],
  },
  {
    id: "business",
    name: "Business & B2B",
    emojis: [
      {
        id: "🤝",
        name: "Handshake",
        keywords: ["deal", "agreement", "partnership"],
        skins: [{src: emojiImagePaths.handshake}],
      },
      {
        id: "💰",
        name: "Money Bag",
        keywords: ["money", "wealth", "profit"],
        skins: [{src: emojiImagePaths.moneyBag}],
      },
      {
        id: "🏢",
        name: "Office Building",
        keywords: ["building", "business", "corporate"],
        skins: [{src: emojiImagePaths.officeBuilding}],
      },
      {
        id: "📉",
        name: "Downward Trend",
        keywords: ["decline", "loss", "business"],
        skins: [{src: emojiImagePaths.downwardTrend}],
      },
      {
        id: "💹",
        name: "Stock Market Up",
        keywords: ["growth", "business", "investment"],
        skins: [{src: emojiImagePaths.stockMarketUp}],
      },
    ],
  },
  {
    id: "teams",
    name: "Teams & Collaboration",
    emojis: [
      {
        id: "👩‍💻",
        name: "Woman Technologist",
        keywords: ["developer", "tech", "coding"],
        skins: [{src: emojiImagePaths.womanTechnologist}],
      },
    ],
  },
  {
    id: "general",
    name: "General Tools & Work",
    emojis: [
      {
        id: "🔧",
        name: "Wrench",
        keywords: ["tools", "fix", "repair"],
        skins: [{src: emojiImagePaths.wrench}],
      },
    ],
  },
];
